dist: focal
sudo: true
language: python
python:
    - "3.9"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install libpthread-stubs0-dev
  - pip install -r requirements.txt
  - pip install pyquickhelper --no-deps
before_script:
  - gcc --version
  - export PYTHONPATH=src
  - python setup.py build_ext --inplace
script:
  - python setup.py unittests
